### ISSUE TITLE
there are a lot of issues with android.support.v7.app library 

### ISSUE THREAD

**Issue by EgyptianM** [gi097/Chat-API#1]
hello friend gi097
when trying to  build the project I got a lot of errors as the screenshot shows

![image](https://cloud.githubusercontent.com/assets/12565380/9955961/10e9dc76-5df5-11e5-864b-9c125c51999a.png)

and when I tried to import it to android studio as I didn't work with eclipse before I got that error

 * Project WhatsApp:D:\Android Programming\Chat-API-master\project.properties:
Library reference ..\design could not be found
Path is D:\Android Programming\Chat-API-master\..\design which resolves to D:\Android Programming\design

please check it out 
and consider that I'm a beginner in android programming
thanks

**Comment by gi097** [comment]
You need to add the android support library to your project's dependencies. Read more here:

https://developer.android.com/tools/support-library/setup.html

Regards.

**Comment by EgyptianM** [comment]
thank you for your quick answer 
can you please switch to android studio?
as you know by the end of this year google will no more support eclipse

**Comment by gi097** [comment]
I simply hate Android Service and I love eclipse, so no.

**Comment by EgyptianM** [comment]
thanks
is there any tutorial to how to add the android support library to your project's dependencies?
as I told before I never used eclipse before and don't know anything about it
sorry for my lots of questions

**Comment by gi097** [comment]
Read my previous posted link, everything is explained there.

**Comment by EgyptianM** [comment]
thank you 
I added it 
but still have 90 errors

![image](https://cloud.githubusercontent.com/assets/12565380/9956944/c0635536-5dfc-11e5-9dcf-2ae859b38877.png)

**Comment by gi097** [comment]
You need to add the Android Design library too.

**Comment by EgyptianM** [comment]
added it but still have errors
![image](https://cloud.githubusercontent.com/assets/12565380/9957059/85388f20-5dfd-11e5-9790-94f3eefebde2.png)

tell me all libs I need to add if you please

**Comment by EgyptianM** [comment]
R.java file is empty

![image](https://cloud.githubusercontent.com/assets/12565380/9957140/101bd282-5dfe-11e5-9a3a-ccaef587e426.png)
